title: Tori's Blog
description: Writ 350 Writing for Digital Media.
show_downloads: false
google_analytics:
theme: jekyll-theme-merlot

remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one